# Generated by Django 4.1.5 on 2023-02-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(max_length=120)),
                ('cuerpo', models.CharField(max_length=1200)),
                ('autor', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
                ('imagen', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('usuario', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('clave', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=80)),
            ],
        ),
    ]
